HOST: http://sunsern.apiary.io/

--- Hint Server ---
---
Hint server generates and manages hints and PG files.
---

--
PG Resources
--
List products added into your shopping-cart. (comment block again in Markdown)
GET /pg{?path}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/students/1", "username":"johndoe", "source_pg":,"testProblems/problem1.pg", "current_html": "<html></html>" }
] }


-- Hint Resources --
Retrieve a hint snippet
GET /hints/{pg_id}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/students/1", "username":"johndoe", "source_pg":,"testProblems/problem1.pg", "current_html": "<html></html>" }
] }

Submit a new hint snippet
POST /hints/{pg_id}
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }

Delete a hint
DELETE /hints/{hint_id}
< 200
{ "result": "done" }

-- Rendering and Answer checking --
Render a PG problem into HTML format
POST /render
{ "source_pg": "DOCUMENT()..." }
< 200
{ "rendered_html": "<div>...</div>" }

Check answers of a PG problem
POST /checkanswer
{ "source_pg": "DOCUMENT()...", "answers": [ "AnSwEr0001": "1", "AnSwEr0002": "2"] }
< 200
{ "results": [0, 1] }

